# Radu-Andrei Dumitrescu 2021

build:
	javac Crypto.java
	javac Valley.java
	javac Stocks.java
	javac Ridge.java

run-p1: Crypto.class
	java Crypto

run-p2: Stocks.class
	java Stocks

run-p3: Valley.class
	java Valley
	

run-p4: Ridge.class
	java Ridge

clean:
	rm *.class
