# Radu-Andrei Dumitrescu 2021

build:
	javac Crypto.java
	javac Valley.java

run-p1: Crypto.class
	java Crypto

run-p2:      # nume necesar

run-p3: Valley.class
	java Valley
	

run-p4:      # nume necesar

clean:		 # nume necesar
